import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "@/styles/globals.css";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`
    ${geistSans.variable}
    ${geistMono.variable}
    antialiased
    grid
    grid-rows-[44px_auto]
    min-h-screen
  `}
			>
				<header className="bg-slate-950 px-2 gap-2 flex justify-between items-center">
					<Link href="/">
						<Image src="/rainstorm.png" alt="rainstorm" width={150} height={167}></Image>
					</Link>
					<nav className="flex gap-2">
						<Link href="/about">About</Link>
						<Link href="/templates">Templates</Link>
						<Link href="/ideas">Ideas</Link>
					</nav>
				</header>
				<main className="bg-slate-900 h-full p-2">{children}</main>
				{/* <footer className="bg-slate-950">footer</footer> */}
			</body>
		</html>
	);
}
