import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`
    ${geistSans.variable}
    ${geistMono.variable}
    antialiased
    grid
    grid-rows-[44px_auto_24px]
    min-h-screen
  `}
			>
				<header className="bg-black p-2">
					<nav className="flex gap-2">
						<Link href="/">Home</Link>
						<Link href="/about">About</Link>
						<Link href="/templates">Templates</Link>
						<Link href="/ideas">Ideas</Link>
					</nav>
				</header>
				<main className="h-full p-2">{children}</main>
				<footer className="bg-black">footer</footer>
			</body>
		</html>
	);
}
