import { Category } from "./ideas";
import { WordBankName } from "./wordBanks";

export interface Template {
	id: string;
	name: string;
	categories: Category[];
	activeBanks?: WordBankName[];
	highlighted: boolean;
}

// TEMPLATES
export const defaultTemplates: Template[] = [
	{
		id: "empty",
		name: "Empty",
		highlighted: true,
		categories: [{ id: "Empty", name: "Empty", text: "", words: [] }],
		activeBanks: ["abstract", "adjective", "verb", "emotion", "nature", "place", "time"],
	},
	{
		id: "song",
		name: "Song",
		highlighted: true,
		categories: [
			{ id: "theme", name: "Theme", text: "", words: [] },
			{ id: "sound", name: "Sound", text: "", words: [] },
			{ id: "genre", name: "Genre", text: "", words: [] },
		],
		activeBanks: [
			"verb",
			"adjective",
			"objects",
			"place",
			"abstract",
			"time",
			"emotion",
			"action",
			"relationship",
			"nature",
			"animal",
			"anatomy",
			"sound",
		],
	},
	{
		id: "story",
		name: "Story",
		highlighted: true,
		categories: [
			{ id: "intro", name: "Introduction", text: "", words: [] },
			{ id: "conflict", name: "Conflict", text: "", words: [] },
			{ id: "resolution", name: "Resolution", text: "", words: [] },
		],
		activeBanks: [
			"verb",
			"adjective",
			"objects",
			"people",
			"place",
			"time",
			"emotion",
			"action",
			"society",
			"relationship",
			"nature",
			"animal",
			"conflict",
			"mystery",
		],
	},
	{
		id: "game",
		name: "Game",
		highlighted: true,
		categories: [
			{ id: "hook", name: "Hook", text: "", words: [] },
			{ id: "loop", name: "Loop", text: "", words: [] },
			{ id: "win", name: "Win", text: "", words: [] },
		],
		activeBanks: [
			"verb",
			"abstract",
			"adjective",
			"creature",
			"emotion",
			"nature",
			"action",
			"conflict",
		],
	},
	{
		id: "full",
		name: "Full",
		highlighted: false,
		categories: [
			{ id: "category1", name: "Category 1", text: "", words: [] },
			{ id: "category2", name: "Category 2", text: "", words: [] },
			{ id: "category3", name: "Category 3", text: "", words: [] },
		],
		activeBanks: [
			"verb",
			"adjective",
			"objects",
			"people",
			"place",
			"abstract",
			"material",
			"time",
			"emotion",
			"action",
			"society",
			"relationship",
			"nature",
			"animal",
			"anatomy",
			"technology",
			"sound",
			"fantasy",
			"creature",
			"scifi",
			"horror",
			"adventure",
			"conflict",
			"mystery",
			"modern",
			"romance",
			"food",
		],
	},
	{
		id: "heros-journey",
		name: "Hero's Journey",
		highlighted: false,
		categories: [
			{ id: "departure", name: "Departure", text: "", words: [] },
			{ id: "initiation", name: "Initiation", text: "", words: [] },
			{ id: "return", name: "Return", text: "", words: [] },
		],
		activeBanks: [
			"abstract",
			"adjective",
			"emotion",
			"nature",
			"place",
			"verb",
			"creature",
			"adventure",
		],
	},
	{
		id: "film-pitch",
		name: "Film Pitch",
		highlighted: false,
		categories: [
			{ id: "protagonist", name: "Protagonist", text: "", words: [] },
			{ id: "setting", name: "Setting", text: "", words: [] },
			{ id: "conflict", name: "Conflict", text: "", words: [] },
			{ id: "theme", name: "Theme", text: "", words: [] },
		],
		activeBanks: ["place", "emotion", "abstract", "verb", "adjective", "conflict"],
	},
	{
		id: "quest",
		name: "Quest",
		highlighted: false,
		categories: [
			{ id: "setting", name: "Setting", text: "", words: [] },
			{ id: "obstacle", name: "Obstacle", text: "", words: [] },
			{ id: "goal", name: "Goal", text: "", words: [] },
			{ id: "reward", name: "Reward", text: "", words: [] },
		],
		activeBanks: ["place", "creature", "emotion", "verb", "adventure", "conflict"],
	},
	{
		id: "dnd-session",
		name: "D&D Session",
		highlighted: false,
		categories: [
			{ id: "goal", name: "Goal", text: "", words: [] },
			{ id: "exploration", name: "Exploration", text: "", words: [] },
			{ id: "challenge", name: "Challenge", text: "", words: [] },
			{ id: "social", name: "Social", text: "", words: [] },
			{ id: "reward", name: "Reward", text: "", words: [] },
		],
		activeBanks: [
			"adjective",
			"adventure",
			"conflict",
			"creature",
			"fantasy",
			"material",
			"mystery",
			"nature",
			"objects",
			"people",
			"place",
			"society",
			"sound",
			"time",
			"verb",
		],
	},
	{
		id: "scifi-adventure",
		name: "Sci-Fi Adventure",
		highlighted: false,
		categories: [
			{ id: "characters", name: "Characters", text: "", words: [] },
			{ id: "ship", name: "Ship / Base", text: "", words: [] },
			{ id: "planet", name: "Planet / Location", text: "", words: [] },
			{ id: "tech", name: "Technology / Artifact", text: "", words: [] },
			{ id: "alien", name: "Alien / Creature", text: "", words: [] },
			{ id: "mission", name: "Mission / Goal", text: "", words: [] },
			{ id: "threat", name: "Threat / Conflict", text: "", words: [] },
		],
		activeBanks: [
			"abstract",
			"adjective",
			"action",
			"adventure",
			"conflict",
			"emotion",
			"modern",
			"objects",
			"people",
			"place",
			"scifi",
			"technology",
			"society",
			"verb",
		],
	},
	{
		id: "romcom",
		name: "Romcom",
		highlighted: false,
		categories: [
			{ id: "characters", name: "Characters", text: "", words: [] },
			{ id: "emotion", name: "Emotion", text: "", words: [] },
			{ id: "action", name: "Action", text: "", words: [] },
			{ id: "setting", name: "Setting", text: "", words: [] },
		],
		activeBanks: ["people", "romance", "emotion", "verb", "adjective", "place", "technology"],
	},
	{
		id: "horror",
		name: "Horror",
		highlighted: false,
		categories: [
			{ id: "location", name: "Location", text: "", words: [] },
			{ id: "characters", name: "Characters", text: "", words: [] },
			{ id: "threat", name: "Threat", text: "", words: [] },
			{ id: "twist", name: "Twist", text: "", words: [] },
		],
		activeBanks: [
			"people",
			"horror",
			"creature",
			"place",
			"conflict",
			"adjective",
			"emotion",
			"verb",
			"abstract",
			"objects",
		],
	},

	{
		id: "mystery",
		name: "Mystery",
		highlighted: false,
		categories: [
			{ id: "setting", name: "Setting", text: "", words: [] },
			{ id: "protagonist", name: "Protagonist", text: "", words: [] },
			{ id: "crime", name: "Crime", text: "", words: [] },
			{ id: "victim", name: "Victim", text: "", words: [] },
			{ id: "clue", name: "Clue", text: "", words: [] },
		],
		activeBanks: [
			"people",
			"mystery",
			"conflict",
			"verb",
			"adjective",
			"action",
			"place",
			"objects",
			"anatomy",
			"emotion",
			"time",
			"material",
		],
	},
];
